### ISSUE TITLE
Problem creating error document

### ISSUE THREAD

**Issue by markvanderlaan** [MarkoMilos/jsonapi#12]
I’m trying to create a document from a request which returns an empty response when the request succeeds but when there is an error it returns a HTTP 401 with the error in json. The problem is i’m not getting a document when the server returns a 401. It only returns a retrofit HttpException with a response with an error body at that moment.
The network call looks like this:

```
@POST("authenticate")
fun authenticate(): Single<Document<Void>>
```

The error body looks like this:
```
{
  "errors": [
    {
      "id": "",
      "status": "401",
      "code": "invalid_credentials",
      "title": "Authentication Failed",
      "detail": "Invalid credentials"
    }
  ]
}
```
Is there anything we are doing wrong? We are using retrofit with RxJava

**Comment by MarkoMilos** [comment]
Hi, this has nothing to do with this library in particular since this library is only for serializing and deserializing JSON.

It would be best if you managed this on the retrofit level while making the call. The retrofit will return `Response<Document<T>>`.

So you need to handle both when this `Response` (retrofit class) has data (deserialized class) or error (you need to handle).

Example utils functions to do so are below (modify them according to your needs). These are mapping the Retrofit `Response` to custom sealed class `Result` that can either be `Success` or `Error`.

```kotlin
fun <T> Response<Document<T>>.responseToResult(): Result<T> {
  if (isSuccessful) {
    // If data exists return success
    val data = body()?.data
    if (data != null) {
      return Result.Success(data)
    }

    // Data does not exist, check if this is a business logic error
    // but the successful response
    val errors = body()?.errors
    if (errors != null) {
      return Result.Error(ApiException(errors))
    }

    // If there is no data or error this is an invalid JsonAPI document
    return Result.Error(Exception("Invalid JsonAPI document. No data or errors!"))
  } else {
    // In case of non 2xx response errors can be present in Response.errorBody
    // but it is not parsed for us. Check if there are API errors and return
    // appropriate failure result with ApiException or default
    val errors = errorsOrNull()
    return if (errors != null) {
      Result.Error(ApiException(errors))
    } else {
      Result.Error(toException())
    }
  }
}

/**
 * Parse [List] of [Error] from Response.errorBody.
 * Returns `null` in case of exception.
 */
fun <T> Response<T>.errorsOrNull(): List<Error>? {
  val errorBodyString = this.errorBody()?.string() ?: return null
  try {
    val errors = errorsAdapter.fromJson(errorBodyString) ?: return null
    return errors
  } catch (e: Exception) {
    return null
  }
}

private val errorsAdapter = Moshi.Builder()....
```
