### ISSUE TITLE
Moshi Codegen

### ISSUE THREAD

**Issue by LeafyLappa** [MarkoMilos/jsonapi#4]
Hello!

Is it possible to make this library work with Moshi codegen?

**Comment by MarkoMilos** [comment]
@LeafyLappa Yes, the library is built so that it can work with Moshi codegen.

If codegen is present/configured it will generate adapters for classes annotated with `@JsonClass(generateAdapter = true)
` and these adapters will be in front of the reflect adapter (`ClassJsonAdapter`) in the adapter chain.

Check out my quick sketch on the following image:

![JSON:API library sketch-Moshi adapters drawio](https://user-images.githubusercontent.com/4303492/163977808-2437bfdc-3c11-4b6d-8308-0a08501cd7f0.png)
