### ISSUE TITLE
Serialize Null values

### ISSUE THREAD

**Issue by jack-collins94** [MarkoMilos/jsonapi#7]
Hey, 

I wanted to find out if it is possible to include the serialization of any null values. Currently, if we have a null value in our object, then the field is not created in the JSON:

Our object currently looks like this:
```
@Resource("item-summary")
data class TransactionResponse(
    @Id val id: String,
    val title: String?,
    val subtitle: String?,
    val datetime: OffsetDateTime,
    val customerId: String,
)
```

If the title and subtitle are null then we get the following JSON:
```
{
    "data": [
        {
            "type": "item-summary",
            "id": "1",
            "attributes": {
                "datetime": "2022-08-17T10:15:45.778832+02:00",
                "customerId": "12",
            }
        }
    ]
}
```

Where we would like it to be:
```
{
    "data": [
        {
            "type": "item-summary",
            "id": "1",
            "attributes": {
               "title":null,
               "subtitle":null,
                "datetime": "2022-08-17T10:15:45.778832+02:00",
                "customerId": "12",
            }
        }
    ]
}
```

**Comment by MarkoMilos** [comment]
Hi,

This is not up to this library since this library will delegate `attributes` serialization to your adapters (generated or custom).

**A) GENERATED ADAPTERS**
If you are using Moshi with reflection then you did not create any adapter explicitly and Moshi uses internal `KotlinJsonAdapter` for Kotlin classes or `ClassJsonAdapter` for Java classes.

If you are using Moshi with codegen then adapters are generated for classes annotated with `@JsonClass(generateAdapter = true)`

Since adapters are generated you don't have fine-grained control over serialization but you can use `serializeNulls()` to wrap generated adapters to ones that will serialize nulls.

Example
```kotlin
 val transactionResponseAdapter = moshi.adapter(...).serializeNulls()
```

If you are not creating adapters yourself you can create a custom annotation to annotate resources for which you want to serialize nulls. 
Example:
```kotlin
@AlwaysSerializeNull
@Resource("item-summary")
data class TransactionResponse(
  @Id val id: String,
  val title: String?,
  val subtitle: String? = null
)
```


A detailed example can be found on Moshi official repository [here](https://github.com/square/moshi/blob/master/examples/src/main/java/com/squareup/moshi/recipes/IncludeNullsForAnnotatedTypes.java)

If you use this Moshi with the Retrofit library you can set `serializeNulls` in `MoshiConverterFactory` constructor.


**B) CUSTOM ADAPTER**
If you wrote a custom adapter, then you have complete control of what to serialize and how. Remember to add the adapter/factory for your custom adapter after the JsonApi.Factory as stated in README.
Example:
```kotlin
Moshi.Builder()
  .add(factory)
  .add(TransactionResponseAdapter())
  .build()
```

**Comment by MarkoMilos** [comment]
Just wrote a quick demo:

```kotlin
fun main() {
  val factory = JsonApiFactory.Builder()
    .addTypes(JsonApi.resources())
    .build()

  val moshi = Moshi.Builder()
    .add(factory)
    .add(AlwaysSerializeNullsFactory())
    .addLast(KotlinJsonAdapterFactory())
    .build()

  val adapter: JsonAdapter<Document<TransactionResponse>> = moshi.adapter(
    Types.newParameterizedType(Document::class.java, TransactionResponse::class.java)
  )

  val transactionResponse = TransactionResponse("1", "title", null)
  val document = Document.from(transactionResponse)
  val json = adapter.toJson(document)

  print(json)
}

@Target(AnnotationTarget.TYPE, AnnotationTarget.CLASS)
@Retention(AnnotationRetention.RUNTIME)
annotation class AlwaysSerializeNulls

class AlwaysSerializeNullsFactory : JsonAdapter.Factory {
  override fun create(type: Type, annotations: MutableSet<out Annotation>, moshi: Moshi): JsonAdapter<*>? {
    val rawType = Types.getRawType(type)
    if (!rawType.isAnnotationPresent(AlwaysSerializeNulls::class.java)) {
      return null
    }
    val delegate: JsonAdapter<Any> = moshi.nextAdapter(this, type, annotations)
    return delegate.serializeNulls()
  }
}

@AlwaysSerializeNulls
@Resource("item-summary")
data class TransactionResponse(
  @Id val id: String,
  val title: String?,
  val subtitle: String?
  // other fields ...
)
```

Running this will output:
```json
{"data":{"type":"item-summary","id":"1","attributes":{"title":"title","subtitle":null}}}
```

**Comment by jack-collins94** [comment]
Thank you so much! Exactly what I was looking for
